[tool.poetry]
name = "pyxvis"
version = "0.1.0a10s"
description = "Python package for Xvis toolbox"
authors = ["Christian Pieringer <8143906+cpieringer@users.noreply.github.com>", "Domingo Mery <dmery@ing.puc.cl>"]
license = "GPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.6.1, <4.0"
numpy = "^1.18"
matplotlib = "^3.3.2"
scipy = "^1.5.2"
pyqt5 = "^5.15.1"
pybalu = "^0.2.9"
opencv-python = "^4.5.1"
opencv-contrib-python = "^4.5.1"
tensorflow = "^2.3"
scikit-learn = "^0.22.2"
scikit-image = "^0.17.2"
pandas = "^1.1.2"
mlxtend = "^0.18.0"
seaborn = "^0.11.1"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
pytest = "^6.2.1"
ipykernel = "^5.4.3"
jupyter-contrib-nbextensions = "^0.5.1"
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry>=0.12.10"]
build-backend = "poetry.masonry.api"
